[2023-12-05 22:13:27,944] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:13:27] "[35m[1mGET /riscos HTTP/1.1[0m" 500 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:13:43,297] WARNING get_riscos() L150  Erro ao consultar os riscos com erro QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r), Não foi possível consultar os riscos:/QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r) - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\app.py L150 
[2023-12-05 22:13:43,298] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:13:43] "[35m[1mGET /riscos HTTP/1.1[0m" 500 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:13:58,267] WARNING get_riscos() L150  Erro ao consultar os riscos com erro QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r), Não foi possível consultar os riscos:/QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r) - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\app.py L150 
[2023-12-05 22:13:58,268] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:13:58] "[35m[1mGET /riscos HTTP/1.1[0m" 500 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:14:22,305] WARNING get_riscos() L150  Erro ao consultar os riscos com erro QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r), Não foi possível consultar os riscos:/QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r) - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\app.py L150 
[2023-12-05 22:14:22,306] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:14:22] "[35m[1mGET /riscos HTTP/1.1[0m" 500 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:15:27,997] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:15:27] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:15:29,287] WARNING get_riscos() L150  Erro ao consultar os riscos com erro QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r), Não foi possível consultar os riscos:/QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r) - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\app.py L150 
[2023-12-05 22:15:29,288] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:15:29] "[35m[1mGET /riscos HTTP/1.1[0m" 500 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:15:59,614] WARNING get_riscos() L150  Erro ao consultar os riscos com erro QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r), Não foi possível consultar os riscos:/QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r) - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\app.py L150 
[2023-12-05 22:15:59,615] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:15:59] "[35m[1mGET /riscos HTTP/1.1[0m" 500 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:19:12,283] WARNING get_riscos() L150  Erro ao consultar os riscos com erro QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r), Não foi possível consultar os riscos:/QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r) - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\app.py L150 
[2023-12-05 22:19:12,284] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:19:12] "[35m[1mGET /riscos HTTP/1.1[0m" 500 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:20:04,997] WARNING get_riscos() L150  Erro ao consultar os riscos com erro QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r), Não foi possível consultar os riscos:/QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r) - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\app.py L150 
[2023-12-05 22:20:04,998] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:20:04] "[35m[1mGET /riscos HTTP/1.1[0m" 500 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:20:35,306] WARNING get_riscos() L150  Erro ao consultar os riscos com erro QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r), Não foi possível consultar os riscos:/QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r) - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\app.py L150 
[2023-12-05 22:20:35,307] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:20:35] "[35m[1mGET /riscos HTTP/1.1[0m" 500 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:20:35,321] WARNING get_riscos() L150  Erro ao consultar os riscos com erro QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r), Não foi possível consultar os riscos:/QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r) - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\app.py L150 
[2023-12-05 22:20:35,322] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:20:35] "[35m[1mGET /riscos HTTP/1.1[0m" 500 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:20:54,293] WARNING get_riscos() L150  Erro ao consultar os riscos com erro QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r), Não foi possível consultar os riscos:/QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r) - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\app.py L150 
[2023-12-05 22:20:54,294] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:20:54] "[35m[1mGET /riscos HTTP/1.1[0m" 500 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:21:05,649] WARNING get_riscos() L150  Erro ao consultar os riscos com erro QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r), Não foi possível consultar os riscos:/QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r) - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\app.py L150 
[2023-12-05 22:21:05,649] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:21:05] "[35m[1mGET /riscos HTTP/1.1[0m" 500 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:21:35,964] WARNING get_riscos() L150  Erro ao consultar os riscos com erro QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r), Não foi possível consultar os riscos:/QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r) - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\app.py L150 
[2023-12-05 22:21:35,964] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:21:35] "[35m[1mGET /riscos HTTP/1.1[0m" 500 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
